/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.services.model.Bus;

import com.services.service.BusLocalServiceUtil;

/**
 * The extended model base implementation for the Bus service. Represents a row in the &quot;JPB_Bus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BusImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see BusImpl
 * @see com.services.model.Bus
 * @generated
 */
public abstract class BusBaseImpl extends BusModelImpl implements Bus {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bus model instance should use the {@link Bus} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			BusLocalServiceUtil.addBus(this);
		}
		else {
			BusLocalServiceUtil.updateBus(this);
		}
	}
}