/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Agency service. Represents a row in the &quot;JPB_Agency&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.AgencyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.AgencyImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see Agency
 * @see com.services.model.impl.AgencyImpl
 * @see com.services.model.impl.AgencyModelImpl
 * @generated
 */
public interface AgencyModel extends BaseModel<Agency> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a agency model instance should use the {@link Agency} interface instead.
	 */

	/**
	 * Returns the primary key of this agency.
	 *
	 * @return the primary key of this agency
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this agency.
	 *
	 * @param primaryKey the primary key of this agency
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the agency ID of this agency.
	 *
	 * @return the agency ID of this agency
	 */
	public long getAgencyId();

	/**
	 * Sets the agency ID of this agency.
	 *
	 * @param agencyId the agency ID of this agency
	 */
	public void setAgencyId(long agencyId);

	/**
	 * Returns the agency name of this agency.
	 *
	 * @return the agency name of this agency
	 */
	@AutoEscape
	public String getAgencyName();

	/**
	 * Sets the agency name of this agency.
	 *
	 * @param agencyName the agency name of this agency
	 */
	public void setAgencyName(String agencyName);

	/**
	 * Returns the owner of this agency.
	 *
	 * @return the owner of this agency
	 */
	@AutoEscape
	public String getOwner();

	/**
	 * Sets the owner of this agency.
	 *
	 * @param owner the owner of this agency
	 */
	public void setOwner(String owner);

	/**
	 * Returns the contact number of this agency.
	 *
	 * @return the contact number of this agency
	 */
	@AutoEscape
	public String getContactNumber();

	/**
	 * Sets the contact number of this agency.
	 *
	 * @param contactNumber the contact number of this agency
	 */
	public void setContactNumber(String contactNumber);

	/**
	 * Returns the email of this agency.
	 *
	 * @return the email of this agency
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this agency.
	 *
	 * @param email the email of this agency
	 */
	public void setEmail(String email);

	/**
	 * Returns the active of this agency.
	 *
	 * @return the active of this agency
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this agency is active.
	 *
	 * @return <code>true</code> if this agency is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this agency is active.
	 *
	 * @param active the active of this agency
	 */
	public void setActive(boolean active);

	/**
	 * Returns the create date of this agency.
	 *
	 * @return the create date of this agency
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this agency.
	 *
	 * @param createDate the create date of this agency
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this agency.
	 *
	 * @return the modified date of this agency
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this agency.
	 *
	 * @param modifiedDate the modified date of this agency
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.Agency agency);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.Agency> toCacheModel();

	@Override
	public com.services.model.Agency toEscapedModel();

	@Override
	public com.services.model.Agency toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}