/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BusAvailability service. Represents a row in the &quot;JPB_BusAvailability&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.BusAvailabilityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.BusAvailabilityImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see BusAvailability
 * @see com.services.model.impl.BusAvailabilityImpl
 * @see com.services.model.impl.BusAvailabilityModelImpl
 * @generated
 */
public interface BusAvailabilityModel extends BaseModel<BusAvailability> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bus availability model instance should use the {@link BusAvailability} interface instead.
	 */

	/**
	 * Returns the primary key of this bus availability.
	 *
	 * @return the primary key of this bus availability
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bus availability.
	 *
	 * @param primaryKey the primary key of this bus availability
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ba ID of this bus availability.
	 *
	 * @return the ba ID of this bus availability
	 */
	public long getBaId();

	/**
	 * Sets the ba ID of this bus availability.
	 *
	 * @param baId the ba ID of this bus availability
	 */
	public void setBaId(long baId);

	/**
	 * Returns the brt ID of this bus availability.
	 *
	 * @return the brt ID of this bus availability
	 */
	public long getBrtId();

	/**
	 * Sets the brt ID of this bus availability.
	 *
	 * @param brtId the brt ID of this bus availability
	 */
	public void setBrtId(long brtId);

	/**
	 * Returns the total of this bus availability.
	 *
	 * @return the total of this bus availability
	 */
	public long getTotal();

	/**
	 * Sets the total of this bus availability.
	 *
	 * @param total the total of this bus availability
	 */
	public void setTotal(long total);

	/**
	 * Returns the available of this bus availability.
	 *
	 * @return the available of this bus availability
	 */
	public long getAvailable();

	/**
	 * Sets the available of this bus availability.
	 *
	 * @param available the available of this bus availability
	 */
	public void setAvailable(long available);

	/**
	 * Returns the price of this bus availability.
	 *
	 * @return the price of this bus availability
	 */
	public long getPrice();

	/**
	 * Sets the price of this bus availability.
	 *
	 * @param price the price of this bus availability
	 */
	public void setPrice(long price);

	/**
	 * Returns the create date of this bus availability.
	 *
	 * @return the create date of this bus availability
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this bus availability.
	 *
	 * @param createDate the create date of this bus availability
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BusAvailability busAvailability);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BusAvailability> toCacheModel();

	@Override
	public BusAvailability toEscapedModel();

	@Override
	public BusAvailability toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}