/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BusEmployee service. Represents a row in the &quot;JPB_BusEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.BusEmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.BusEmployeeImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see BusEmployee
 * @see com.services.model.impl.BusEmployeeImpl
 * @see com.services.model.impl.BusEmployeeModelImpl
 * @generated
 */
public interface BusEmployeeModel extends BaseModel<BusEmployee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bus employee model instance should use the {@link BusEmployee} interface instead.
	 */

	/**
	 * Returns the primary key of this bus employee.
	 *
	 * @return the primary key of this bus employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bus employee.
	 *
	 * @param primaryKey the primary key of this bus employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the be ID of this bus employee.
	 *
	 * @return the be ID of this bus employee
	 */
	public long getBeId();

	/**
	 * Sets the be ID of this bus employee.
	 *
	 * @param beId the be ID of this bus employee
	 */
	public void setBeId(long beId);

	/**
	 * Returns the be name of this bus employee.
	 *
	 * @return the be name of this bus employee
	 */
	@AutoEscape
	public String getBeName();

	/**
	 * Sets the be name of this bus employee.
	 *
	 * @param beName the be name of this bus employee
	 */
	public void setBeName(String beName);

	/**
	 * Returns the agency of this bus employee.
	 *
	 * @return the agency of this bus employee
	 */
	public long getAgency();

	/**
	 * Sets the agency of this bus employee.
	 *
	 * @param agency the agency of this bus employee
	 */
	public void setAgency(long agency);

	/**
	 * Returns the contact number of this bus employee.
	 *
	 * @return the contact number of this bus employee
	 */
	@AutoEscape
	public String getContactNumber();

	/**
	 * Sets the contact number of this bus employee.
	 *
	 * @param contactNumber the contact number of this bus employee
	 */
	public void setContactNumber(String contactNumber);

	/**
	 * Returns the email of this bus employee.
	 *
	 * @return the email of this bus employee
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this bus employee.
	 *
	 * @param email the email of this bus employee
	 */
	public void setEmail(String email);

	/**
	 * Returns the license number of this bus employee.
	 *
	 * @return the license number of this bus employee
	 */
	@AutoEscape
	public String getLicenseNumber();

	/**
	 * Sets the license number of this bus employee.
	 *
	 * @param licenseNumber the license number of this bus employee
	 */
	public void setLicenseNumber(String licenseNumber);

	/**
	 * Returns the alternate ID number of this bus employee.
	 *
	 * @return the alternate ID number of this bus employee
	 */
	@AutoEscape
	public String getAlternateIdNumber();

	/**
	 * Sets the alternate ID number of this bus employee.
	 *
	 * @param alternateIdNumber the alternate ID number of this bus employee
	 */
	public void setAlternateIdNumber(String alternateIdNumber);

	/**
	 * Returns the active of this bus employee.
	 *
	 * @return the active of this bus employee
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this bus employee is active.
	 *
	 * @return <code>true</code> if this bus employee is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this bus employee is active.
	 *
	 * @param active the active of this bus employee
	 */
	public void setActive(boolean active);

	/**
	 * Returns the create date of this bus employee.
	 *
	 * @return the create date of this bus employee
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this bus employee.
	 *
	 * @param createDate the create date of this bus employee
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bus employee.
	 *
	 * @return the modified date of this bus employee
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bus employee.
	 *
	 * @param modifiedDate the modified date of this bus employee
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.BusEmployee busEmployee);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.BusEmployee> toCacheModel();

	@Override
	public com.services.model.BusEmployee toEscapedModel();

	@Override
	public com.services.model.BusEmployee toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}