/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Bus service. Represents a row in the &quot;JPB_Bus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.BusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.BusImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see Bus
 * @see com.services.model.impl.BusImpl
 * @see com.services.model.impl.BusModelImpl
 * @generated
 */
public interface BusModel extends BaseModel<Bus> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bus model instance should use the {@link Bus} interface instead.
	 */

	/**
	 * Returns the primary key of this bus.
	 *
	 * @return the primary key of this bus
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bus.
	 *
	 * @param primaryKey the primary key of this bus
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bus ID of this bus.
	 *
	 * @return the bus ID of this bus
	 */
	public long getBusId();

	/**
	 * Sets the bus ID of this bus.
	 *
	 * @param busId the bus ID of this bus
	 */
	public void setBusId(long busId);

	/**
	 * Returns the bus name of this bus.
	 *
	 * @return the bus name of this bus
	 */
	@AutoEscape
	public String getBusName();

	/**
	 * Sets the bus name of this bus.
	 *
	 * @param busName the bus name of this bus
	 */
	public void setBusName(String busName);

	/**
	 * Returns the agency of this bus.
	 *
	 * @return the agency of this bus
	 */
	public long getAgency();

	/**
	 * Sets the agency of this bus.
	 *
	 * @param agency the agency of this bus
	 */
	public void setAgency(long agency);

	/**
	 * Returns the driver of this bus.
	 *
	 * @return the driver of this bus
	 */
	public long getDriver();

	/**
	 * Sets the driver of this bus.
	 *
	 * @param driver the driver of this bus
	 */
	public void setDriver(long driver);

	/**
	 * Returns the conductor of this bus.
	 *
	 * @return the conductor of this bus
	 */
	public long getConductor();

	/**
	 * Sets the conductor of this bus.
	 *
	 * @param conductor the conductor of this bus
	 */
	public void setConductor(long conductor);

	/**
	 * Returns the helper of this bus.
	 *
	 * @return the helper of this bus
	 */
	public long getHelper();

	/**
	 * Sets the helper of this bus.
	 *
	 * @param helper the helper of this bus
	 */
	public void setHelper(long helper);

	/**
	 * Returns the plate number of this bus.
	 *
	 * @return the plate number of this bus
	 */
	@AutoEscape
	public String getPlateNumber();

	/**
	 * Sets the plate number of this bus.
	 *
	 * @param plateNumber the plate number of this bus
	 */
	public void setPlateNumber(String plateNumber);

	/**
	 * Returns the color of this bus.
	 *
	 * @return the color of this bus
	 */
	@AutoEscape
	public String getColor();

	/**
	 * Sets the color of this bus.
	 *
	 * @param color the color of this bus
	 */
	public void setColor(String color);

	/**
	 * Returns the make of this bus.
	 *
	 * @return the make of this bus
	 */
	@AutoEscape
	public String getMake();

	/**
	 * Sets the make of this bus.
	 *
	 * @param make the make of this bus
	 */
	public void setMake(String make);

	/**
	 * Returns the model of this bus.
	 *
	 * @return the model of this bus
	 */
	@AutoEscape
	public String getModel();

	/**
	 * Sets the model of this bus.
	 *
	 * @param model the model of this bus
	 */
	public void setModel(String model);

	/**
	 * Returns the year of this bus.
	 *
	 * @return the year of this bus
	 */
	@AutoEscape
	public String getYear();

	/**
	 * Sets the year of this bus.
	 *
	 * @param year the year of this bus
	 */
	public void setYear(String year);

	/**
	 * Returns the active of this bus.
	 *
	 * @return the active of this bus
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this bus is active.
	 *
	 * @return <code>true</code> if this bus is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this bus is active.
	 *
	 * @param active the active of this bus
	 */
	public void setActive(boolean active);

	/**
	 * Returns the create date of this bus.
	 *
	 * @return the create date of this bus
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this bus.
	 *
	 * @param createDate the create date of this bus
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bus.
	 *
	 * @return the modified date of this bus
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bus.
	 *
	 * @param modifiedDate the modified date of this bus
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.Bus bus);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.Bus> toCacheModel();

	@Override
	public com.services.model.Bus toEscapedModel();

	@Override
	public com.services.model.Bus toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}