/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BusRoute service. Represents a row in the &quot;JPB_BusRoute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.BusRouteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.BusRouteImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see BusRoute
 * @see com.services.model.impl.BusRouteImpl
 * @see com.services.model.impl.BusRouteModelImpl
 * @generated
 */
public interface BusRouteModel extends BaseModel<BusRoute> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bus route model instance should use the {@link BusRoute} interface instead.
	 */

	/**
	 * Returns the primary key of this bus route.
	 *
	 * @return the primary key of this bus route
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bus route.
	 *
	 * @param primaryKey the primary key of this bus route
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the br ID of this bus route.
	 *
	 * @return the br ID of this bus route
	 */
	public long getBrId();

	/**
	 * Sets the br ID of this bus route.
	 *
	 * @param brId the br ID of this bus route
	 */
	public void setBrId(long brId);

	/**
	 * Returns the bus ID of this bus route.
	 *
	 * @return the bus ID of this bus route
	 */
	public long getBusId();

	/**
	 * Sets the bus ID of this bus route.
	 *
	 * @param busId the bus ID of this bus route
	 */
	public void setBusId(long busId);

	/**
	 * Returns the start location of this bus route.
	 *
	 * @return the start location of this bus route
	 */
	public long getStartLocation();

	/**
	 * Sets the start location of this bus route.
	 *
	 * @param startLocation the start location of this bus route
	 */
	public void setStartLocation(long startLocation);

	/**
	 * Returns the end location of this bus route.
	 *
	 * @return the end location of this bus route
	 */
	public long getEndLocation();

	/**
	 * Sets the end location of this bus route.
	 *
	 * @param endLocation the end location of this bus route
	 */
	public void setEndLocation(long endLocation);

	/**
	 * Returns the mid location1 of this bus route.
	 *
	 * @return the mid location1 of this bus route
	 */
	public long getMidLocation1();

	/**
	 * Sets the mid location1 of this bus route.
	 *
	 * @param midLocation1 the mid location1 of this bus route
	 */
	public void setMidLocation1(long midLocation1);

	/**
	 * Returns the mid location2 of this bus route.
	 *
	 * @return the mid location2 of this bus route
	 */
	public long getMidLocation2();

	/**
	 * Sets the mid location2 of this bus route.
	 *
	 * @param midLocation2 the mid location2 of this bus route
	 */
	public void setMidLocation2(long midLocation2);

	/**
	 * Returns the active of this bus route.
	 *
	 * @return the active of this bus route
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this bus route is active.
	 *
	 * @return <code>true</code> if this bus route is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this bus route is active.
	 *
	 * @param active the active of this bus route
	 */
	public void setActive(boolean active);

	/**
	 * Returns the create date of this bus route.
	 *
	 * @return the create date of this bus route
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this bus route.
	 *
	 * @param createDate the create date of this bus route
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bus route.
	 *
	 * @return the modified date of this bus route
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bus route.
	 *
	 * @param modifiedDate the modified date of this bus route
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.BusRoute busRoute);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.BusRoute> toCacheModel();

	@Override
	public com.services.model.BusRoute toEscapedModel();

	@Override
	public com.services.model.BusRoute toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}