/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BusRouteTimings service. Represents a row in the &quot;JPB_BusRouteTimings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.BusRouteTimingsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.BusRouteTimingsImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see BusRouteTimings
 * @see com.services.model.impl.BusRouteTimingsImpl
 * @see com.services.model.impl.BusRouteTimingsModelImpl
 * @generated
 */
public interface BusRouteTimingsModel extends BaseModel<BusRouteTimings> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bus route timings model instance should use the {@link BusRouteTimings} interface instead.
	 */

	/**
	 * Returns the primary key of this bus route timings.
	 *
	 * @return the primary key of this bus route timings
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bus route timings.
	 *
	 * @param primaryKey the primary key of this bus route timings
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the brt ID of this bus route timings.
	 *
	 * @return the brt ID of this bus route timings
	 */
	public long getBrtId();

	/**
	 * Sets the brt ID of this bus route timings.
	 *
	 * @param brtId the brt ID of this bus route timings
	 */
	public void setBrtId(long brtId);

	/**
	 * Returns the br ID of this bus route timings.
	 *
	 * @return the br ID of this bus route timings
	 */
	public long getBrId();

	/**
	 * Sets the br ID of this bus route timings.
	 *
	 * @param brId the br ID of this bus route timings
	 */
	public void setBrId(long brId);

	/**
	 * Returns the bus details of this bus route timings.
	 *
	 * @return the bus details of this bus route timings
	 */
	@AutoEscape
	public String getBusDetails();

	/**
	 * Sets the bus details of this bus route timings.
	 *
	 * @param busDetails the bus details of this bus route timings
	 */
	public void setBusDetails(String busDetails);

	/**
	 * Returns the travel date of this bus route timings.
	 *
	 * @return the travel date of this bus route timings
	 */
	@AutoEscape
	public String getTravelDate();

	/**
	 * Sets the travel date of this bus route timings.
	 *
	 * @param travelDate the travel date of this bus route timings
	 */
	public void setTravelDate(String travelDate);

	/**
	 * Returns the travel time of this bus route timings.
	 *
	 * @return the travel time of this bus route timings
	 */
	@AutoEscape
	public String getTravelTime();

	/**
	 * Sets the travel time of this bus route timings.
	 *
	 * @param travelTime the travel time of this bus route timings
	 */
	public void setTravelTime(String travelTime);

	/**
	 * Returns the total of this bus route timings.
	 *
	 * @return the total of this bus route timings
	 */
	public long getTotal();

	/**
	 * Sets the total of this bus route timings.
	 *
	 * @param total the total of this bus route timings
	 */
	public void setTotal(long total);

	/**
	 * Returns the available of this bus route timings.
	 *
	 * @return the available of this bus route timings
	 */
	public long getAvailable();

	/**
	 * Sets the available of this bus route timings.
	 *
	 * @param available the available of this bus route timings
	 */
	public void setAvailable(long available);

	/**
	 * Returns the price of this bus route timings.
	 *
	 * @return the price of this bus route timings
	 */
	public long getPrice();

	/**
	 * Sets the price of this bus route timings.
	 *
	 * @param price the price of this bus route timings
	 */
	public void setPrice(long price);

	/**
	 * Returns the active of this bus route timings.
	 *
	 * @return the active of this bus route timings
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this bus route timings is active.
	 *
	 * @return <code>true</code> if this bus route timings is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this bus route timings is active.
	 *
	 * @param active the active of this bus route timings
	 */
	public void setActive(boolean active);

	/**
	 * Returns the completed of this bus route timings.
	 *
	 * @return the completed of this bus route timings
	 */
	@AutoEscape
	public String getCompleted();

	/**
	 * Sets the completed of this bus route timings.
	 *
	 * @param completed the completed of this bus route timings
	 */
	public void setCompleted(String completed);

	/**
	 * Returns the create date of this bus route timings.
	 *
	 * @return the create date of this bus route timings
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this bus route timings.
	 *
	 * @param createDate the create date of this bus route timings
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.BusRouteTimings busRouteTimings);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.BusRouteTimings> toCacheModel();

	@Override
	public com.services.model.BusRouteTimings toEscapedModel();

	@Override
	public com.services.model.BusRouteTimings toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}