/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Coupon service. Represents a row in the &quot;JPB_Coupon&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.CouponModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.CouponImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see Coupon
 * @see com.services.model.impl.CouponImpl
 * @see com.services.model.impl.CouponModelImpl
 * @generated
 */
public interface CouponModel extends BaseModel<Coupon> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a coupon model instance should use the {@link Coupon} interface instead.
	 */

	/**
	 * Returns the primary key of this coupon.
	 *
	 * @return the primary key of this coupon
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this coupon.
	 *
	 * @param primaryKey the primary key of this coupon
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the coupon ID of this coupon.
	 *
	 * @return the coupon ID of this coupon
	 */
	public long getCouponId();

	/**
	 * Sets the coupon ID of this coupon.
	 *
	 * @param couponId the coupon ID of this coupon
	 */
	public void setCouponId(long couponId);

	/**
	 * Returns the coupon name of this coupon.
	 *
	 * @return the coupon name of this coupon
	 */
	@AutoEscape
	public String getCouponName();

	/**
	 * Sets the coupon name of this coupon.
	 *
	 * @param couponName the coupon name of this coupon
	 */
	public void setCouponName(String couponName);

	/**
	 * Returns the price of this coupon.
	 *
	 * @return the price of this coupon
	 */
	public long getPrice();

	/**
	 * Sets the price of this coupon.
	 *
	 * @param price the price of this coupon
	 */
	public void setPrice(long price);

	/**
	 * Returns the valid till of this coupon.
	 *
	 * @return the valid till of this coupon
	 */
	public Date getValidTill();

	/**
	 * Sets the valid till of this coupon.
	 *
	 * @param validTill the valid till of this coupon
	 */
	public void setValidTill(Date validTill);

	/**
	 * Returns the audience of this coupon.
	 *
	 * @return the audience of this coupon
	 */
	public boolean getAudience();

	/**
	 * Returns <code>true</code> if this coupon is audience.
	 *
	 * @return <code>true</code> if this coupon is audience; <code>false</code> otherwise
	 */
	public boolean isAudience();

	/**
	 * Sets whether this coupon is audience.
	 *
	 * @param audience the audience of this coupon
	 */
	public void setAudience(boolean audience);

	/**
	 * Returns the create date of this coupon.
	 *
	 * @return the create date of this coupon
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this coupon.
	 *
	 * @param createDate the create date of this coupon
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.Coupon coupon);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.Coupon> toCacheModel();

	@Override
	public com.services.model.Coupon toEscapedModel();

	@Override
	public com.services.model.Coupon toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}