/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserCoupon service. Represents a row in the &quot;JPB_UserCoupon&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.services.model.impl.UserCouponModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.services.model.impl.UserCouponImpl}.
 * </p>
 *
 * @author Ankur Srivastava
 * @see UserCoupon
 * @see com.services.model.impl.UserCouponImpl
 * @see com.services.model.impl.UserCouponModelImpl
 * @generated
 */
public interface UserCouponModel extends BaseModel<UserCoupon> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user coupon model instance should use the {@link UserCoupon} interface instead.
	 */

	/**
	 * Returns the primary key of this user coupon.
	 *
	 * @return the primary key of this user coupon
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user coupon.
	 *
	 * @param primaryKey the primary key of this user coupon
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uc ID of this user coupon.
	 *
	 * @return the uc ID of this user coupon
	 */
	public long getUcId();

	/**
	 * Sets the uc ID of this user coupon.
	 *
	 * @param ucId the uc ID of this user coupon
	 */
	public void setUcId(long ucId);

	/**
	 * Returns the user ID of this user coupon.
	 *
	 * @return the user ID of this user coupon
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user coupon.
	 *
	 * @param userId the user ID of this user coupon
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user coupon.
	 *
	 * @return the user uuid of this user coupon
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user coupon.
	 *
	 * @param userUuid the user uuid of this user coupon
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the coupon ID of this user coupon.
	 *
	 * @return the coupon ID of this user coupon
	 */
	public long getCouponId();

	/**
	 * Sets the coupon ID of this user coupon.
	 *
	 * @param couponId the coupon ID of this user coupon
	 */
	public void setCouponId(long couponId);

	/**
	 * Returns the claimed of this user coupon.
	 *
	 * @return the claimed of this user coupon
	 */
	public boolean getClaimed();

	/**
	 * Returns <code>true</code> if this user coupon is claimed.
	 *
	 * @return <code>true</code> if this user coupon is claimed; <code>false</code> otherwise
	 */
	public boolean isClaimed();

	/**
	 * Sets whether this user coupon is claimed.
	 *
	 * @param claimed the claimed of this user coupon
	 */
	public void setClaimed(boolean claimed);

	/**
	 * Returns the create date of this user coupon.
	 *
	 * @return the create date of this user coupon
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user coupon.
	 *
	 * @param createDate the create date of this user coupon
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.services.model.UserCoupon userCoupon);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.services.model.UserCoupon> toCacheModel();

	@Override
	public com.services.model.UserCoupon toEscapedModel();

	@Override
	public com.services.model.UserCoupon toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}